### ISSUE TITLE
Not able to install.

### ISSUE THREAD

**Issue by andersonamuller** [Pinpickle/tight#12]
I followed the instructions to install and I didn't get any error, but yeoman is not able to recognize the generator after it is installed. It does work with other generators.

**Comment by Pinpickle** [comment]
Oh dear! I was having this in testing and assumed it was something weird with my `npm link` setup. Just tried a global install again and had the issue you were describing.

**Comment by Pinpickle** [comment]
So it turns out that most of the files aren't getting published to npm

``` bash
mkdir tight
cd tight
npm install generator-tight
cd node_modules/generator-tight
ls
node_modules  package.json  README.md #missing lib/ and generators/ and a lot of other stuff
```

Haven't worked out why just yet... as this doesn't have a `.npmignore` file.

**Comment by Pinpickle** [comment]
[`generator-generator`](https://github.com/yeoman/generator-generator) sets the `files` attribute for `package.json` to just the `app` directory - this project has changed from the default structure! Just had to add `generators` and `lib` to that array and now everything is working.

@andersonamuller try `npm update -g generator-tight` and then `yo tight`, it should work now!

**Comment by andersonamuller** [comment]
Thank you, it's working.
