### ISSUE TITLE
Need to check that Composer is installed globally before trying to use it

### ISSUE THREAD

**Issue by mdcanham** [Pinpickle/tight#16]
If Composer is not installed we get the following error:

```
Running composer install
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn composer ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by Pinpickle** [comment]
We do make a note is made of this in the readme:

> You're going to need to have the command line version of [Composer](http://getcomposer.org) installed (so no `php composer.phar` business), and [Node.js/npm](http://nodejs.org). This uses [Yeoman](http://yeoman.io/) and [Gulp](http://gulpjs.com) (and potentially [Bower](http://bower.io)), so you're going to want to have those installed.

However, this does lead to a crash _mid generator_, which is all kinds of bad so a check should be done before the generator starts. The bigger issue is with Bower as this it necessarily required but that can only be determined when the user reaches theme generation and answers config. Users shouldn't be forced to install software they don't actually need.

The same goes for #17
