### ISSUE TITLE
Class Extension not found

### ISSUE THREAD

**Issue by kromakollision** [Pinpickle/tight#25]
Any idea what could be causing this error?

> Fatal error: Uncaught Error: Class 'Kromakollision\testproject\Extension' not found in /home/u860129147/public_html/index.php:35 Stack trace: #0 {main} thrown in /home/u860129147/public_html/index.php on line 35

'Kromakollision' and 'testproject' are the values I entered while running the generator.

Locally everything works fine. This error occurs after I upload the files to the server. Unzipping the site-bundle didn't work, so I unzipped it locally and uploaded manually.

I'm not familiar with this php namespacing thing..

**Comment by Pinpickle** [comment]
Ohh this is a longstanding bug, extension files are not uploaded to the server correctly.

Sorry about the delay, I'll get this sorted

**Comment by Pinpickle** [comment]
@kromakollision I've fixed it upstream but as you've already generated your project, I'll tell you what to do

In `gulpfile.js`, you're going to want to add an extra element to the `appDeploy` array on line 49. Simply the string `'./src/**/*.php',` will do. See an example in [the template file](https://github.com/Pinpickle/tight/blob/master/generators/app/templates/gulpfile.js#L68).
